# Develop override settings

# url: http://192.168.1.200:4000
url: http://0.0.0.0:4000

analytics:
  provider: false

comments:
  disqus:
    shortname            : "mmistakes-dev"

sass:
  style: expanded
